---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
    dpi = 300
)
```

# `{epl}`

<!-- badges: start -->
<!-- badges: end -->

`{epl}` is a repository of functions and scripts for common tasks for use 
by students in the UBC Environmental Physiology Laboratory.

## Installation

You can install the development version of `{epl}` from
[GitHub](https://github.com/jemarnold/epl) with:

``` r
# install.packages("remotes")
remotes::install_github("jemarnold/epl")
```

## Online App

`<coming soon>`

## Usage

### Read Tymewear Data

```{r}
#| eval: false

library(epl)

file_path <- file.path("Tymewear", "Raw Data", "my_file.csv")

read_tymelive(file_path)
#> $data
#> # A tibble: 1,083 × 5
#>     time timestamp              br    vt    ve
#>    <dbl> <dttm>              <dbl> <dbl> <dbl>
#>  1  0    2025-10-23 10:50:11   127   135    17
#>  2  4.14 2025-10-23 10:50:15   149   135    20
#>  3  7.95 2025-10-23 10:50:18   150   105    16
#>  4 13.0  2025-10-23 10:50:24   138   240    33
#>  5 17.2  2025-10-23 10:50:28   133   111    15
#>  6 21.2  2025-10-23 10:50:32   128   163    21
#>  7 25.7  2025-10-23 10:50:36   130   361    47
#>  8 33.9  2025-10-23 10:50:44   119   588    70
#>  9 39.3  2025-10-23 10:50:50    80   114     9
#> 10 44.7  2025-10-23 10:50:55   100   221    22
#> # ℹ 1,073 more rows
#> 
#> $details
#> # A tibble: 60 × 2
#>    ...1          ...2    
#>    <chr>         <chr>   
#>  1 Info Section  ""      
#>  2 type          "0"     
#>  3 stages        "[]"    
#>  4 gender        "Male"
#>  5 weight        "85.0"  
#>  6 weight_units  "SI"    
#>  7 activity-name "id03"  
#>  8 f_v           "1.0"   
#>  9 activity-type "0"     
#> 10 sport         "2"     
#> # ℹ 50 more rows

```
